In [1]:
# difference between linear eq and non linear eq 
# eq of lines 
# eq of plane
# eq of circle
# binomial  
# distributions
# conditional probability

In [31]:
def palindrome(num):
    num = str(num)
    if num == num[::-1]:
        return num+" True"
    else:
        num = int(num)+1
        return palindrome(num)

In [32]:
palindrome(121)

'121 True'

In [33]:
palindrome(123)

'131 True'

In [40]:
def a_scramble(str1,str2):
    for x in str2:
        if x.lower() not in str1.lower():
            return False
    return True

In [41]:
a_scramble("Tom Marvolo Riddle","Voldemort")

True

In [42]:
a_scramble("ticket","chat")

False

In [66]:
from math import sqrt

def isPerfectSquare(x):
    s = int(sqrt(x))
    return s*s == x

def check_fib(num):
    return isPerfectSquare(5 * num * num + 4) or isPerfectSquare(5 * num * num - 4)

In [69]:
check_fib(377)

True

In [97]:
def compress(word):
    temp = {}
    compression = ''
    for x in word:
        if x in temp.keys():
            temp[x] = temp[x] + 1
        else:
            temp[x] = 1   
    for (key, value) in temp.items():
        compression = compression + (key+str(value))
    return compression

In [99]:
compress('xxcccdex')

'x3c3d1e1'

In [145]:
def compress_successive(word):
        length_word = len(word)
        count = 1
        s = ""
        for i in range(length_word-1):
            if word[i] == word[i+1]:
                count = count + 1
                if i + 1 == length_word-1:
                    s = s + word[i+1] + str(count)
            else:
                s = s + word[i]+str(count)
                count = 1
                if i + 1 == length_word-1:
                    s = s + word[i+1] + str(count)

            #print(s)
        return s

In [147]:
compress_successive('xxxxxnnnnxxxmmmmwwwwax')

'x5n4x3m4w4a1x1'

In [157]:
#Code starts here

#Function to compress string
def compress_3(word):
    word=word.lower()
    mist=[]
    l=0
    while(l<len(word)):
        m=word[l]
        j=0
        while(l<len(word) and word[l]==m):
                j=j+1
                l=l+1

        mist.append(m)
        mist.append(str(j))

    return ''.join(mist)

In [159]:
compress_3('xxxxxnnnnxxxmmmmwwwwax')

'x5n4x3m4w4a1x1'

In [161]:
#### pandas

import pandas as pd

df = pd.read_csv('/Users/03000070/Downloads/dc_airbnb.csv')

df.head()

  host_response_rate host_acceptance_rate  ...  zipcode  state
0                92%                  91%  ...    20003     DC
1                90%                 100%  ...    20003     DC
2                90%                 100%  ...    20782     MD
3               100%                  NaN  ...    20024     DC
4                92%                  67%  ...    20910     MD

[5 rows x 19 columns]

In [163]:
df.shape

(3723, 19)

In [164]:
df['city'].value_counts()

Washington                         3628
Washington, D.C.                     63
Silver Spring                         8
Takoma Park                           6
Mount Rainier                         5
Hyattsville                           2
Washington                            2
Capitol Hill, Washington              1
Columbia Heights, middle of DC!       1
Dupont Circle                         1
Annapolis                             1
Capitol Heights                       1
Arlington                             1
chevy chase                           1
Adams Morgan                          1
New York                              1
Name: city, dtype: int64

In [165]:
df['state'].value_counts()

DC               3696
MD                 24
Washington DC       1
NY                  1
VA                  1
Name: state, dtype: int64

In [166]:
df['zipcode'].value_counts()

20009         715
20001         508
20002         502
20010         284
20003         273
20011         197
20007         174
20005         171
20037         139
20008         129
20017          98
20024          77
20020          75
20016          70
20036          65
20018          50
20012          46
20019          38
20015          28
20006          18
20032          15
20910           8
20912           6
20712           5
20004           4
20052           4
20064           3
20782           2
20007-3413      1
21403           1
20002-6645      1
20003-3021      1
20268           1
20229           1
20743           1
20001-4044      1
22209           1
20815           1
Name: zipcode, dtype: int64

In [171]:
df = pd.read_excel('/Users/03000070/Downloads/python_hackathon/pandas_guided_project/data/excel-comp-data.xlsx')

In [172]:
df.head()

   account                         name  ...     Feb    Mar
0   211829   Kerluke, Koepp and Hilpert  ...   62000  35000
1   320563               Walter-Trantow  ...   45000  35000
2   648336   Bashirian, Kunde and Price  ...  120000  35000
3   109996  D'Amore, Gleichner and Bode  ...  120000  10000
4   121213                Bauch-Goldner  ...  120000  35000

[5 rows x 9 columns]

In [173]:
df['state'] = df['state'].str.lower()

In [175]:
df['state'].head()

0            texas
1    northcarolina
2             iowa
3            maine
4       california
Name: state, dtype: object

In [176]:
df['total'] = df['Jan'] + df['Feb'] + df['Mar']

In [177]:
df.head()

   account                         name  ...    Mar   total
0   211829   Kerluke, Koepp and Hilpert  ...  35000  107000
1   320563               Walter-Trantow  ...  35000  175000
2   648336   Bashirian, Kunde and Price  ...  35000  246000
3   109996  D'Amore, Gleichner and Bode  ...  10000  175000
4   121213                Bauch-Goldner  ...  35000  317000

[5 rows x 10 columns]

In [178]:
sum_row = df['total'].sum()

In [179]:
sum_row

3686000

In [188]:
list(df)[-4:]

['Jan', 'Feb', 'Mar', 'total']

In [183]:
df[list(df)[-4:]].sum()

Jan      1462000
Feb      1507000
Mar       717000
total    3686000
dtype: int64

In [186]:
df[list(df)[-4:]].sum().sum()

7372000

In [189]:
df[list(df)[-4:]].sum()

Jan      1462000
Feb      1507000
Mar       717000
total    3686000
dtype: int64

In [190]:
sum_row = df[["Jan","Feb","Mar","total"]].sum()

In [193]:
sum_row = pd.DataFrame(sum_row)

In [194]:
sum_row

             0
Jan    1462000
Feb    1507000
Mar     717000
total  3686000

In [195]:
sum_row = pd.DataFrame(sum_row).T

In [196]:
sum_row

       Jan      Feb     Mar    total
0  1462000  1507000  717000  3686000

In [197]:
pd.concat([df,sum_row])

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

        Feb      Jan  ...                                street    total
0     62000    10000  ...                    34456 Sean Highway   107000
1     45000    95000  ...                     1311 Alvis Tunnel   175000
2    120000    91000  ...  62184 Schamberger Underpass Apt. 231   246000
3    120000    45000  ...           155 Fadel Crescent Apt. 144   175000
4    120000   162000  ...                   7274 Marissa Common   317000
5    120000   150000  ...                  89403 Casimer Spring   305000
6    120000    62000  ...          340 Consuela Bridge Apt. 400   252000
7     95000   145000  ...          91971 Cronin Vista Suite 601   275000
8     95000    70000  ...                      26739 Grant Lock   200000
9    120000    70000  ...             366 Maggio Grove Apt. 998   225000
10   120000    45000  ...             649 Cierra Forks Apt. 078   220000
11    10000   150000  ...              18115 Olivine Throughway   322000
12   120000   162000  ...                       182 Bertie Road   317000
13   120000    55000  ...                  2624 Beatty Parkways   210000
14   120000   150000  ...                 8917 Bergstrom Meadow   340000
0   1507000  1462000  ...                                   NaN  3686000

[16 rows x 10 columns]

In [ ]:
#another way to do it
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# load the dataset
df = pd.read_csv('/Users/03000070/Downloads/python_hackathon/pandas_guided_project/data/excel-comp-data.xlsx')

# convert state column in lower case
df['state'] = df['state'].apply(lambda x: x.lower())

# Calculate the total
df["total"] = df["Jan"] + df["Feb"] + df["Mar"]

# sum of amount
sum_row = df[["Jan", "Feb", "Mar", "total"]].sum()

# append the row
df_final = df.append(sum_row, ignore_index=True)

In [212]:
url = "https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations"

In [213]:
import requests

In [214]:
response = requests.get(url)

In [218]:
df1 = pd.read_html(response.content)[0]

   Codes:  ISO ISO 3166 codes (2-letter, 3-letter, and 3-digit codes from ISO 3166-1; 2+2-letter codes from ISO 3166-2)  ANSI 2-letter and 2-digit codes from the ANSI standard INCITS 38:2009  USPS 2-letter codes used by the United States Postal Service  USCG 2-letter codes used by the United States Coast Guard (red text shows differences between ANSI and USCG) Abbreviations:  GPO Older variable-length official US Government Printing Office abbreviations  AP Abbreviations from the AP Stylebook (red text shows differences between GPO and AP)  ... Codes:  ISO ISO 3166 codes (2-letter, 3-letter, and 3-digit codes from ISO 3166-1; 2+2-letter codes from ISO 3166-2)  ANSI 2-letter and 2-digit codes from the ANSI standard INCITS 38:2009  USPS 2-letter codes used by the United States Postal Service  USCG 2-letter codes used by the United States Coast Guard (red text shows differences between ANSI and USCG) Abbreviations:  GPO Older variable-length official US Government Printing Office abbreviations  AP Abbreviations from the AP Stylebook (red text shows differences between GPO and AP).9
0                                              Codes:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
1                                                 ISO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
2                                                ANSI                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
3                                                USPS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
4                                                USCG                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
5                                      Abbreviations:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
6                                                 GPO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
7                                                  AP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
8                           Name and status of region                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                 Otherabbreviations
9                                                 NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                 Otherabbreviations
10                           United States of America                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                             U.S.A.
11                                            Alabama                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
12                                             Alaska                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                              Alas.
13                                            Arizona                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                Az.
14                                           Arkansas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
15                                         California                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                          Ca., Cal.
16                                           Colorado                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                               Col.
17                                        Connecticut                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                Ct.
18                                           Delaware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                De.
19                               District of Columbia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                         Wash. D.C.
20                                            Florida                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                         Fl., Flor.
21                                            Georgia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                               Geo.
22                                             Hawaii                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                               H.I.
23                                              Idaho                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                          Id., Ida.
24                                           Illinois                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                  Il., Ills., Ill's
25                                            Indiana                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                In.
26                                               Iowa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                       Ia., Ioa.[a]
27                                             Kansas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                           Ks., Ka.
28                                           Kentucky                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                     Ken., Kent.[b]
29                                          Louisiana                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
..                                                ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                ...

In [221]:
df1 = df1.iloc[11:]

In [222]:
df1

   Codes:  ISO ISO 3166 codes (2-letter, 3-letter, and 3-digit codes from ISO 3166-1; 2+2-letter codes from ISO 3166-2)  ANSI 2-letter and 2-digit codes from the ANSI standard INCITS 38:2009  USPS 2-letter codes used by the United States Postal Service  USCG 2-letter codes used by the United States Coast Guard (red text shows differences between ANSI and USCG) Abbreviations:  GPO Older variable-length official US Government Printing Office abbreviations  AP Abbreviations from the AP Stylebook (red text shows differences between GPO and AP)  ... Codes:  ISO ISO 3166 codes (2-letter, 3-letter, and 3-digit codes from ISO 3166-1; 2+2-letter codes from ISO 3166-2)  ANSI 2-letter and 2-digit codes from the ANSI standard INCITS 38:2009  USPS 2-letter codes used by the United States Postal Service  USCG 2-letter codes used by the United States Coast Guard (red text shows differences between ANSI and USCG) Abbreviations:  GPO Older variable-length official US Government Printing Office abbreviations  AP Abbreviations from the AP Stylebook (red text shows differences between GPO and AP).9
22                                             Hawaii                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                               H.I.
23                                              Idaho                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                          Id., Ida.
24                                           Illinois                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                  Il., Ills., Ill's
25                                            Indiana                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                In.
26                                               Iowa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                       Ia., Ioa.[a]
27                                             Kansas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                           Ks., Ka.
28                                           Kentucky                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                     Ken., Kent.[b]
29                                          Louisiana                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
30                                              Maine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                Me.
31                                           Maryland                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
32                                      Massachusetts                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
33                                           Michigan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
34                                          Minnesota                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                Mn.
35                                        Mississippi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
36                                           Missouri                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
37                                            Montana                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
38                                           Nebraska                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
39                                             Nevada                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                Nv.
40                                      New Hampshire                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                NaN
41                                         New Jersey                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                           N.Jersey
42                                         New Mexico                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                             New M.
43                                           New York                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                            N. York
44                                     North Carolina                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                            N. Car.
45                                       North Dakota                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                              NoDak
46                                               Ohio                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                            O., Oh.
47                                           Oklahoma                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                Ok.
48                                             Oregon                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                Or.
49                                       Pennsylvania                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                      Penn., Penna.
50                                       Rhode Island                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                               R.I. & P.P., R. Isl.
51                                     South Carolina                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                            S. Car.
..                                                ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...                                                ...

In [224]:
# next challenge

df2 = pd.read_csv('/Users/03000070/Downloads/python_hackathon/pandas_guided_project/data/scraped.csv')

In [226]:
df2.head()

   Unnamed: 0 United States of America  ... Unnamed: 14 Unnamed: 15
0          12                  Alabama  ...         NaN         NaN
1          13                   Alaska  ...         NaN         NaN
2          14                  Arizona  ...         NaN         NaN
3          15                 Arkansas  ...         NaN         NaN
4          16               California  ...         NaN         NaN

[5 rows x 16 columns]

In [232]:
state = df2['United States of America'].tolist()
abbr = df.iloc[:,6]

In [235]:
mapping = dict(zip(state,abbr))

In [237]:
# permutation combination
# central limit theorems CLT
# partial differentiation

In [238]:
mapping

{'Alabama': nan,
 'Alaska': nan,
 'Arizona': nan,
 'Arkansas': nan,
 'California': nan,
 'Colorado': nan,
 'Connecticut': nan,
 'Delaware': nan,
 'DistrictofColumbia': 'USCG',
 'Florida': nan,
 'Georgia': nan,
 'Hawaii': 'AL',
 'Idaho': 'AK',
 'Illinois': 'AZ',
 'Indiana': 'AR',
 'Iowa': 'CF',
 'Kansas': 'CL',
 'Kentucky': 'CT',
 'Louisiana': 'DL',
 'Maine': 'DC',
 'Maryland': 'FL',
 'Massachusetts': 'GA',
 'Michigan': 'HA',
 'Minnesota': 'ID',
 'Mississippi': 'IL',
 'Missouri': 'IN',
 'Montana': 'IA',
 'Nebraska': nan,
 'Nevada': 'KY',
 'NewHampshire': 'LA',
 'NewJersey': 'ME',
 'NewMexico': 'MD',
 'NewYork': 'MS',
 'NorthCarolina': 'MC',
 'NorthDakota': 'MN',
 'Ohio': 'MI',
 'Oklahoma': 'MO',
 'Oregon': 'MT',
 'Pennsylvania': 'NB',
 'RhodeIsland': 'NV',
 'SouthCarolina': 'NH',
 'SouthDakota': 'NJ',
 'Tennessee': 'NM',
 'Texas': 'NY',
 'Utah': 'NC',
 'Vermont': 'ND',
 'Virginia': 'OH',
 'Washington': 'OK',
 'WestVirginia': 'OR',
 'Wisconsin': 'PA',
 'Wyoming': 'RI',
 'AmericanSamoa': 'SC',
 'Guam': 'SD',
 'NorthernMarianaIslands': nan,
 'PuertoRico': 'TX',
 'U.S.VirginIslands': 'UT',
 'U.S.MinorOutlyingIslands': 'VT',
 'BakerIsland': 'VA',
 'HowlandIsland': 'WN',
 'JarvisIsland': 'WV',
 'JohnstonAtoll': 'WS',
 'KingmanReef': 'WY',
 'MidwayIslands': 'AS',
 'NavassaIsland': 'GU',
 'PalmyraAtoll[c]': 'CM',
 'WakeIsland': 'PR',
 'Micronesia': 'VI',
 'MarshallIslands': nan,
 'Palau': nan,
 'U.S.ArmedForces–Americas[d]': nan,
 'U.S.ArmedForces–Europe[e]': nan,
 'U.S.ArmedForces–Pacific[f]': nan,
 'PanamaCanalZone': nan,
 'PhilippineIslands': nan,
 'TrustTerritoryofthePacificIslands': nan}