In [6]:
countries = ['India','Srilanka','Bangladesh','Pakistan']

capital = ['Delhi','Colombo','Dhaka','Islamabad']


countries_capital = {}

In [8]:
countries_capital = dict(zip(countries,capital))

In [9]:
countries_capital

{'India': 'Delhi',
 'Srilanka': 'Colombo',
 'Bangladesh': 'Dhaka',
 'Pakistan': 'Islamabad'}

In [12]:
temp = {}
for i,j in countries, capital :

ValueError: too many values to unpack (expected 2)

In [14]:
num_1 = list(range(1,101))

In [15]:
num_1

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [16]:
temp = []
for x in num_1:
    if x%3==0 and x%4==0:
        temp.append(x)

In [17]:
temp

[12, 24, 36, 48, 60, 72, 84, 96]

In [18]:
temp_1 = [i for i in num_1 if i%3==0 and i%4==0]

In [19]:
temp_1

[12, 24, 36, 48, 60, 72, 84, 96]

In [20]:
num_list = list(range(1,100))

In [21]:
num_list

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [26]:
# this is odd numbers

prime_num = []
for i in num_list :
    if i%2==1:
        prime_num.append(i)

In [27]:
prime_num

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

In [28]:
#prime number

prime_nums=[]
for x in num_1:
   count=0
   for i in range(1,x+1):
       if x%i==0:
           count=count+1
   if count==2:
       prime_nums.append(x)

In [29]:
prime_nums

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [57]:
num_1 = list(range(1,100))
print(num_1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

In [63]:
new_list1 = []

for x in num_1:
    if x%2==0:
        new_list1.append(x)
#         print("Even",x)
    else:
        new_list1.append((x**x))
#         print("Odd",x*x)

In [64]:
new_list1

[1,
 2,
 27,
 4,
 3125,
 6,
 823543,
 8,
 387420489,
 10,
 285311670611,
 12,
 302875106592253,
 14,
 437893890380859375,
 16,
 827240261886336764177,
 18,
 1978419655660313589123979,
 20,
 5842587018385982521381124421,
 22,
 20880467999847912034355032910567,
 24,
 88817841970012523233890533447265625,
 26,
 443426488243037769948249630619149892803,
 28,
 2567686153161211134561828214731016126483469,
 30,
 17069174130723235958610643029059314756044734431,
 32,
 129110040087761027839616029934664535539337183380513,
 34,
 1102507499354148695951786433413508348166942596435546875,
 36,
 10555134955777783414078330085995832946127396083370199442517,
 38,
 112595147462071192539789448988889059930192105219196517009951959,
 40,
 1330877630632711998713399240963346255985889330161650994325137953641,
 42,
 17343773367030267519903781288812032158308062539012091953077767198995507,
 44,
 248063644451341145494649182395412689744530581492654164321720600128173828125,
 46,
 3877924263464448622666648186154330754898344901344205917642325627886496385062863,
 48,
 66009724686219550843768321818371771650147004059278069406814190436565131829325062449,
 50,
 1219211305094648479473193481872927834667576992593770717189298225284399541977208231315051,
 52,
 24356848165022712132477606520104725518533453128685640844505130879576720609150223301256150373,
 54,
 524744532468751923546122657597368049278513737089035272057324643668607677682302892208099365234375,
 56,
 12158129736671364080886280192352136280305445908985401876990335800107686586023081377754367704855688057,
 58,
 302182066535432255614734701333399524449282910532282724655138380663835618264136459996754463358299552427939,
 60,
 8037480562545943774063961638435258139453693382991023311670379647429452389091570630196571368048020948560431661,
 62,
 228273036346967044979900512337165522400819024722490933829954793073267717315004135590642802687246850771579138342847,
 64,
 6908252164760920851405538694468286082230378724259454186289117297729987129104901877330036086277686990797519683837890625,
 66,
 222337020242360576812569226538683753874082408437758291741262115823894811650848346334502642370010973465496690788650052277723,
 68,
 7596040312163297274222442578208043236112279041839441308045514203595638030283176823539793587591372230230103933110810192201741429,
 70,
 275006373483461607657434076627252658495183350017755660813753981774508905998081919405140568848353397233796618192645698819765129996471,
 72,
 10533405146807286720373659460502060785759379112212598116064998418834781689316645387966435364502141349866164216580595609788325190062013833,
 74,
 426181657761258833198605424151960757395791315610122269092300199179088043392834051588896184557263865748388820264835885609500110149383544921875,
 76,
 18188037387806198379277339915556929647807403283187048631478337739929618787870634227045716719924575689062274471430368865388203540672666042530996797,
 78,
 817598737071050959409276229318696698168591900537987468276932073768901912096673342793217657607316423968313726492566673678273923566086786121551339775919,
 80,
 38662196978715633273404758790074316960214213096178319621856934259807530937321861485192508542873470637501160980081794035970219670238407078788135931371782481,
 82,
 1920797877785042297826876342398329981366626138903106707239638623062073160162030496354441554187075110650838449453108757445590084411555537438824653742747212640587,
 84,
 100140253328453899494506997059845948876248360208192710258703340107188607793155063635811515105559240430619077757390331456723193970237417715907213278114795684814453125,
 86,
 5472364007515806092890840962213361933646557867359955457554369346343376220574263169290566361924999277451198802156950364045812455566817070274944448633167362192918054601383,
 88,
 313119843606264301926053344163576361349265045995115651405929697601914062309331717222037671868698420619053704956499930323034173850662765737986672484408801585719796136592384409,
 90,
 18739875497044403588343023979942190913870699099585922106152367184893220649019310617359174987694158429118066514085327846177870674743597929299970612055662195817332948573029136642691,
 92,
 1171963849265444210417582587751248824708146148109809710033315342359111701761656602431435296049358716378517967896050409107202745103300944452206991034477139649315017364735008987336482893,
 94,
 76514281153818492497108910522923939889608448570427803043646059567958108943618778356292728753731576478313833091931623635414286047187179783985819399826089348692903513438068330287933349609375,
 96,
 5210245939718361468048211048414496022534389576033913164940029913016568215580398296261072019231723279851007241838011659882766685337218633992220688288491655299087016195985205218347711578485744737,
 98,
 369729637649726772657187905628805440595668764281741102430259972423552570455277523421410650010128232727940978889548326540119429996769494359451621570193644014418071060667659301384999779999159200499899]